name: torch_rl
channels:
  - defaults
dependencies:
  - ca-certificates=2024.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.14
  - python=3.9.19
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.4
      - packaging==24.1
      - pillow==10.4.0
      - pip==24.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - six==1.16.0
      - sympy==1.13.1
      - tensordict-nightly==2024.4.24
      - torch==2.2.2
      - torchrl-nightly==2024.4.24
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - zipp==3.19.2